/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MathIndexRouteImport } from './routes/math.index'
import { Route as EvsIndexRouteImport } from './routes/evs.index'
import { Route as EnglishIndexRouteImport } from './routes/english.index'
import { Route as MathTimesTablesRouteImport } from './routes/math.times-tables'
import { Route as MathShapesRouteImport } from './routes/math.shapes'
import { Route as MathPlaceValueRouteImport } from './routes/math.place-value'
import { Route as MathNumbersRouteImport } from './routes/math.numbers'
import { Route as MathCountingRouteImport } from './routes/math.counting'
import { Route as MathCompareRouteImport } from './routes/math.compare'
import { Route as MathAddsubRouteImport } from './routes/math.addsub'
import { Route as EvsWeatherRouteImport } from './routes/evs.weather'
import { Route as EvsRoutinesRouteImport } from './routes/evs.routines'
import { Route as EvsPlantsRouteImport } from './routes/evs.plants'
import { Route as EvsFoodRouteImport } from './routes/evs.food'
import { Route as EvsFamilyRouteImport } from './routes/evs.family'
import { Route as EvsEmotionsRouteImport } from './routes/evs.emotions'
import { Route as EvsBodyRouteImport } from './routes/evs.body'
import { Route as EvsAnimalsRouteImport } from './routes/evs.animals'
import { Route as EnglishTracingRouteImport } from './routes/english.tracing'
import { Route as EnglishSpellingRouteImport } from './routes/english.spelling'
import { Route as EnglishSightWordsRouteImport } from './routes/english.sight-words'
import { Route as EnglishSentencesRouteImport } from './routes/english.sentences'
import { Route as EnglishDigraphsRouteImport } from './routes/english.digraphs'
import { Route as EnglishAlphabetRouteImport } from './routes/english.alphabet'
import { Route as EnglishPhonicsIndexRouteImport } from './routes/english.phonics.index'
import { Route as EnglishPhonicsTrickyWordsRouteImport } from './routes/english.phonics.tricky-words'
import { Route as EnglishPhonicsRhymesRouteImport } from './routes/english.phonics.rhymes'
import { Route as EnglishPhonicsGroup7RouteImport } from './routes/english.phonics.group-7'
import { Route as EnglishPhonicsGroup6RouteImport } from './routes/english.phonics.group-6'
import { Route as EnglishPhonicsGroup5RouteImport } from './routes/english.phonics.group-5'
import { Route as EnglishPhonicsGroup4RouteImport } from './routes/english.phonics.group-4'
import { Route as EnglishPhonicsGroup3RouteImport } from './routes/english.phonics.group-3'
import { Route as EnglishPhonicsGroup2RouteImport } from './routes/english.phonics.group-2'
import { Route as EnglishPhonicsGroup1RouteImport } from './routes/english.phonics.group-1'
import { Route as EnglishPhonicsCvcWordsRouteImport } from './routes/english.phonics.cvc-words'
import { Route as EnglishPhonicsBlendingRouteImport } from './routes/english.phonics.blending'

const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MathIndexRoute = MathIndexRouteImport.update({
  id: '/math/',
  path: '/math/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvsIndexRoute = EvsIndexRouteImport.update({
  id: '/evs/',
  path: '/evs/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishIndexRoute = EnglishIndexRouteImport.update({
  id: '/english/',
  path: '/english/',
  getParentRoute: () => rootRouteImport,
} as any)
const MathTimesTablesRoute = MathTimesTablesRouteImport.update({
  id: '/math/times-tables',
  path: '/math/times-tables',
  getParentRoute: () => rootRouteImport,
} as any)
const MathShapesRoute = MathShapesRouteImport.update({
  id: '/math/shapes',
  path: '/math/shapes',
  getParentRoute: () => rootRouteImport,
} as any)
const MathPlaceValueRoute = MathPlaceValueRouteImport.update({
  id: '/math/place-value',
  path: '/math/place-value',
  getParentRoute: () => rootRouteImport,
} as any)
const MathNumbersRoute = MathNumbersRouteImport.update({
  id: '/math/numbers',
  path: '/math/numbers',
  getParentRoute: () => rootRouteImport,
} as any)
const MathCountingRoute = MathCountingRouteImport.update({
  id: '/math/counting',
  path: '/math/counting',
  getParentRoute: () => rootRouteImport,
} as any)
const MathCompareRoute = MathCompareRouteImport.update({
  id: '/math/compare',
  path: '/math/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const MathAddsubRoute = MathAddsubRouteImport.update({
  id: '/math/addsub',
  path: '/math/addsub',
  getParentRoute: () => rootRouteImport,
} as any)
const EvsWeatherRoute = EvsWeatherRouteImport.update({
  id: '/evs/weather',
  path: '/evs/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const EvsRoutinesRoute = EvsRoutinesRouteImport.update({
  id: '/evs/routines',
  path: '/evs/routines',
  getParentRoute: () => rootRouteImport,
} as any)
const EvsPlantsRoute = EvsPlantsRouteImport.update({
  id: '/evs/plants',
  path: '/evs/plants',
  getParentRoute: () => rootRouteImport,
} as any)
const EvsFoodRoute = EvsFoodRouteImport.update({
  id: '/evs/food',
  path: '/evs/food',
  getParentRoute: () => rootRouteImport,
} as any)
const EvsFamilyRoute = EvsFamilyRouteImport.update({
  id: '/evs/family',
  path: '/evs/family',
  getParentRoute: () => rootRouteImport,
} as any)
const EvsEmotionsRoute = EvsEmotionsRouteImport.update({
  id: '/evs/emotions',
  path: '/evs/emotions',
  getParentRoute: () => rootRouteImport,
} as any)
const EvsBodyRoute = EvsBodyRouteImport.update({
  id: '/evs/body',
  path: '/evs/body',
  getParentRoute: () => rootRouteImport,
} as any)
const EvsAnimalsRoute = EvsAnimalsRouteImport.update({
  id: '/evs/animals',
  path: '/evs/animals',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishTracingRoute = EnglishTracingRouteImport.update({
  id: '/english/tracing',
  path: '/english/tracing',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishSpellingRoute = EnglishSpellingRouteImport.update({
  id: '/english/spelling',
  path: '/english/spelling',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishSightWordsRoute = EnglishSightWordsRouteImport.update({
  id: '/english/sight-words',
  path: '/english/sight-words',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishSentencesRoute = EnglishSentencesRouteImport.update({
  id: '/english/sentences',
  path: '/english/sentences',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishDigraphsRoute = EnglishDigraphsRouteImport.update({
  id: '/english/digraphs',
  path: '/english/digraphs',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishAlphabetRoute = EnglishAlphabetRouteImport.update({
  id: '/english/alphabet',
  path: '/english/alphabet',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishPhonicsIndexRoute = EnglishPhonicsIndexRouteImport.update({
  id: '/english/phonics/',
  path: '/english/phonics/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishPhonicsTrickyWordsRoute =
  EnglishPhonicsTrickyWordsRouteImport.update({
    id: '/english/phonics/tricky-words',
    path: '/english/phonics/tricky-words',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnglishPhonicsRhymesRoute = EnglishPhonicsRhymesRouteImport.update({
  id: '/english/phonics/rhymes',
  path: '/english/phonics/rhymes',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishPhonicsGroup7Route = EnglishPhonicsGroup7RouteImport.update({
  id: '/english/phonics/group-7',
  path: '/english/phonics/group-7',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishPhonicsGroup6Route = EnglishPhonicsGroup6RouteImport.update({
  id: '/english/phonics/group-6',
  path: '/english/phonics/group-6',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishPhonicsGroup5Route = EnglishPhonicsGroup5RouteImport.update({
  id: '/english/phonics/group-5',
  path: '/english/phonics/group-5',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishPhonicsGroup4Route = EnglishPhonicsGroup4RouteImport.update({
  id: '/english/phonics/group-4',
  path: '/english/phonics/group-4',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishPhonicsGroup3Route = EnglishPhonicsGroup3RouteImport.update({
  id: '/english/phonics/group-3',
  path: '/english/phonics/group-3',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishPhonicsGroup2Route = EnglishPhonicsGroup2RouteImport.update({
  id: '/english/phonics/group-2',
  path: '/english/phonics/group-2',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishPhonicsGroup1Route = EnglishPhonicsGroup1RouteImport.update({
  id: '/english/phonics/group-1',
  path: '/english/phonics/group-1',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishPhonicsCvcWordsRoute = EnglishPhonicsCvcWordsRouteImport.update({
  id: '/english/phonics/cvc-words',
  path: '/english/phonics/cvc-words',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishPhonicsBlendingRoute = EnglishPhonicsBlendingRouteImport.update({
  id: '/english/phonics/blending',
  path: '/english/phonics/blending',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/parent': typeof ParentRoute
  '/profiles': typeof ProfilesRoute
  '/english/alphabet': typeof EnglishAlphabetRoute
  '/english/digraphs': typeof EnglishDigraphsRoute
  '/english/sentences': typeof EnglishSentencesRoute
  '/english/sight-words': typeof EnglishSightWordsRoute
  '/english/spelling': typeof EnglishSpellingRoute
  '/english/tracing': typeof EnglishTracingRoute
  '/evs/animals': typeof EvsAnimalsRoute
  '/evs/body': typeof EvsBodyRoute
  '/evs/emotions': typeof EvsEmotionsRoute
  '/evs/family': typeof EvsFamilyRoute
  '/evs/food': typeof EvsFoodRoute
  '/evs/plants': typeof EvsPlantsRoute
  '/evs/routines': typeof EvsRoutinesRoute
  '/evs/weather': typeof EvsWeatherRoute
  '/math/addsub': typeof MathAddsubRoute
  '/math/compare': typeof MathCompareRoute
  '/math/counting': typeof MathCountingRoute
  '/math/numbers': typeof MathNumbersRoute
  '/math/place-value': typeof MathPlaceValueRoute
  '/math/shapes': typeof MathShapesRoute
  '/math/times-tables': typeof MathTimesTablesRoute
  '/english/': typeof EnglishIndexRoute
  '/evs/': typeof EvsIndexRoute
  '/math/': typeof MathIndexRoute
  '/english/phonics/blending': typeof EnglishPhonicsBlendingRoute
  '/english/phonics/cvc-words': typeof EnglishPhonicsCvcWordsRoute
  '/english/phonics/group-1': typeof EnglishPhonicsGroup1Route
  '/english/phonics/group-2': typeof EnglishPhonicsGroup2Route
  '/english/phonics/group-3': typeof EnglishPhonicsGroup3Route
  '/english/phonics/group-4': typeof EnglishPhonicsGroup4Route
  '/english/phonics/group-5': typeof EnglishPhonicsGroup5Route
  '/english/phonics/group-6': typeof EnglishPhonicsGroup6Route
  '/english/phonics/group-7': typeof EnglishPhonicsGroup7Route
  '/english/phonics/rhymes': typeof EnglishPhonicsRhymesRoute
  '/english/phonics/tricky-words': typeof EnglishPhonicsTrickyWordsRoute
  '/english/phonics/': typeof EnglishPhonicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/parent': typeof ParentRoute
  '/profiles': typeof ProfilesRoute
  '/english/alphabet': typeof EnglishAlphabetRoute
  '/english/digraphs': typeof EnglishDigraphsRoute
  '/english/sentences': typeof EnglishSentencesRoute
  '/english/sight-words': typeof EnglishSightWordsRoute
  '/english/spelling': typeof EnglishSpellingRoute
  '/english/tracing': typeof EnglishTracingRoute
  '/evs/animals': typeof EvsAnimalsRoute
  '/evs/body': typeof EvsBodyRoute
  '/evs/emotions': typeof EvsEmotionsRoute
  '/evs/family': typeof EvsFamilyRoute
  '/evs/food': typeof EvsFoodRoute
  '/evs/plants': typeof EvsPlantsRoute
  '/evs/routines': typeof EvsRoutinesRoute
  '/evs/weather': typeof EvsWeatherRoute
  '/math/addsub': typeof MathAddsubRoute
  '/math/compare': typeof MathCompareRoute
  '/math/counting': typeof MathCountingRoute
  '/math/numbers': typeof MathNumbersRoute
  '/math/place-value': typeof MathPlaceValueRoute
  '/math/shapes': typeof MathShapesRoute
  '/math/times-tables': typeof MathTimesTablesRoute
  '/english': typeof EnglishIndexRoute
  '/evs': typeof EvsIndexRoute
  '/math': typeof MathIndexRoute
  '/english/phonics/blending': typeof EnglishPhonicsBlendingRoute
  '/english/phonics/cvc-words': typeof EnglishPhonicsCvcWordsRoute
  '/english/phonics/group-1': typeof EnglishPhonicsGroup1Route
  '/english/phonics/group-2': typeof EnglishPhonicsGroup2Route
  '/english/phonics/group-3': typeof EnglishPhonicsGroup3Route
  '/english/phonics/group-4': typeof EnglishPhonicsGroup4Route
  '/english/phonics/group-5': typeof EnglishPhonicsGroup5Route
  '/english/phonics/group-6': typeof EnglishPhonicsGroup6Route
  '/english/phonics/group-7': typeof EnglishPhonicsGroup7Route
  '/english/phonics/rhymes': typeof EnglishPhonicsRhymesRoute
  '/english/phonics/tricky-words': typeof EnglishPhonicsTrickyWordsRoute
  '/english/phonics': typeof EnglishPhonicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/parent': typeof ParentRoute
  '/profiles': typeof ProfilesRoute
  '/english/alphabet': typeof EnglishAlphabetRoute
  '/english/digraphs': typeof EnglishDigraphsRoute
  '/english/sentences': typeof EnglishSentencesRoute
  '/english/sight-words': typeof EnglishSightWordsRoute
  '/english/spelling': typeof EnglishSpellingRoute
  '/english/tracing': typeof EnglishTracingRoute
  '/evs/animals': typeof EvsAnimalsRoute
  '/evs/body': typeof EvsBodyRoute
  '/evs/emotions': typeof EvsEmotionsRoute
  '/evs/family': typeof EvsFamilyRoute
  '/evs/food': typeof EvsFoodRoute
  '/evs/plants': typeof EvsPlantsRoute
  '/evs/routines': typeof EvsRoutinesRoute
  '/evs/weather': typeof EvsWeatherRoute
  '/math/addsub': typeof MathAddsubRoute
  '/math/compare': typeof MathCompareRoute
  '/math/counting': typeof MathCountingRoute
  '/math/numbers': typeof MathNumbersRoute
  '/math/place-value': typeof MathPlaceValueRoute
  '/math/shapes': typeof MathShapesRoute
  '/math/times-tables': typeof MathTimesTablesRoute
  '/english/': typeof EnglishIndexRoute
  '/evs/': typeof EvsIndexRoute
  '/math/': typeof MathIndexRoute
  '/english/phonics/blending': typeof EnglishPhonicsBlendingRoute
  '/english/phonics/cvc-words': typeof EnglishPhonicsCvcWordsRoute
  '/english/phonics/group-1': typeof EnglishPhonicsGroup1Route
  '/english/phonics/group-2': typeof EnglishPhonicsGroup2Route
  '/english/phonics/group-3': typeof EnglishPhonicsGroup3Route
  '/english/phonics/group-4': typeof EnglishPhonicsGroup4Route
  '/english/phonics/group-5': typeof EnglishPhonicsGroup5Route
  '/english/phonics/group-6': typeof EnglishPhonicsGroup6Route
  '/english/phonics/group-7': typeof EnglishPhonicsGroup7Route
  '/english/phonics/rhymes': typeof EnglishPhonicsRhymesRoute
  '/english/phonics/tricky-words': typeof EnglishPhonicsTrickyWordsRoute
  '/english/phonics/': typeof EnglishPhonicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/parent'
    | '/profiles'
    | '/english/alphabet'
    | '/english/digraphs'
    | '/english/sentences'
    | '/english/sight-words'
    | '/english/spelling'
    | '/english/tracing'
    | '/evs/animals'
    | '/evs/body'
    | '/evs/emotions'
    | '/evs/family'
    | '/evs/food'
    | '/evs/plants'
    | '/evs/routines'
    | '/evs/weather'
    | '/math/addsub'
    | '/math/compare'
    | '/math/counting'
    | '/math/numbers'
    | '/math/place-value'
    | '/math/shapes'
    | '/math/times-tables'
    | '/english/'
    | '/evs/'
    | '/math/'
    | '/english/phonics/blending'
    | '/english/phonics/cvc-words'
    | '/english/phonics/group-1'
    | '/english/phonics/group-2'
    | '/english/phonics/group-3'
    | '/english/phonics/group-4'
    | '/english/phonics/group-5'
    | '/english/phonics/group-6'
    | '/english/phonics/group-7'
    | '/english/phonics/rhymes'
    | '/english/phonics/tricky-words'
    | '/english/phonics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/parent'
    | '/profiles'
    | '/english/alphabet'
    | '/english/digraphs'
    | '/english/sentences'
    | '/english/sight-words'
    | '/english/spelling'
    | '/english/tracing'
    | '/evs/animals'
    | '/evs/body'
    | '/evs/emotions'
    | '/evs/family'
    | '/evs/food'
    | '/evs/plants'
    | '/evs/routines'
    | '/evs/weather'
    | '/math/addsub'
    | '/math/compare'
    | '/math/counting'
    | '/math/numbers'
    | '/math/place-value'
    | '/math/shapes'
    | '/math/times-tables'
    | '/english'
    | '/evs'
    | '/math'
    | '/english/phonics/blending'
    | '/english/phonics/cvc-words'
    | '/english/phonics/group-1'
    | '/english/phonics/group-2'
    | '/english/phonics/group-3'
    | '/english/phonics/group-4'
    | '/english/phonics/group-5'
    | '/english/phonics/group-6'
    | '/english/phonics/group-7'
    | '/english/phonics/rhymes'
    | '/english/phonics/tricky-words'
    | '/english/phonics'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/parent'
    | '/profiles'
    | '/english/alphabet'
    | '/english/digraphs'
    | '/english/sentences'
    | '/english/sight-words'
    | '/english/spelling'
    | '/english/tracing'
    | '/evs/animals'
    | '/evs/body'
    | '/evs/emotions'
    | '/evs/family'
    | '/evs/food'
    | '/evs/plants'
    | '/evs/routines'
    | '/evs/weather'
    | '/math/addsub'
    | '/math/compare'
    | '/math/counting'
    | '/math/numbers'
    | '/math/place-value'
    | '/math/shapes'
    | '/math/times-tables'
    | '/english/'
    | '/evs/'
    | '/math/'
    | '/english/phonics/blending'
    | '/english/phonics/cvc-words'
    | '/english/phonics/group-1'
    | '/english/phonics/group-2'
    | '/english/phonics/group-3'
    | '/english/phonics/group-4'
    | '/english/phonics/group-5'
    | '/english/phonics/group-6'
    | '/english/phonics/group-7'
    | '/english/phonics/rhymes'
    | '/english/phonics/tricky-words'
    | '/english/phonics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRoute
  ParentRoute: typeof ParentRoute
  ProfilesRoute: typeof ProfilesRoute
  EnglishAlphabetRoute: typeof EnglishAlphabetRoute
  EnglishDigraphsRoute: typeof EnglishDigraphsRoute
  EnglishSentencesRoute: typeof EnglishSentencesRoute
  EnglishSightWordsRoute: typeof EnglishSightWordsRoute
  EnglishSpellingRoute: typeof EnglishSpellingRoute
  EnglishTracingRoute: typeof EnglishTracingRoute
  EvsAnimalsRoute: typeof EvsAnimalsRoute
  EvsBodyRoute: typeof EvsBodyRoute
  EvsEmotionsRoute: typeof EvsEmotionsRoute
  EvsFamilyRoute: typeof EvsFamilyRoute
  EvsFoodRoute: typeof EvsFoodRoute
  EvsPlantsRoute: typeof EvsPlantsRoute
  EvsRoutinesRoute: typeof EvsRoutinesRoute
  EvsWeatherRoute: typeof EvsWeatherRoute
  MathAddsubRoute: typeof MathAddsubRoute
  MathCompareRoute: typeof MathCompareRoute
  MathCountingRoute: typeof MathCountingRoute
  MathNumbersRoute: typeof MathNumbersRoute
  MathPlaceValueRoute: typeof MathPlaceValueRoute
  MathShapesRoute: typeof MathShapesRoute
  MathTimesTablesRoute: typeof MathTimesTablesRoute
  EnglishIndexRoute: typeof EnglishIndexRoute
  EvsIndexRoute: typeof EvsIndexRoute
  MathIndexRoute: typeof MathIndexRoute
  EnglishPhonicsBlendingRoute: typeof EnglishPhonicsBlendingRoute
  EnglishPhonicsCvcWordsRoute: typeof EnglishPhonicsCvcWordsRoute
  EnglishPhonicsGroup1Route: typeof EnglishPhonicsGroup1Route
  EnglishPhonicsGroup2Route: typeof EnglishPhonicsGroup2Route
  EnglishPhonicsGroup3Route: typeof EnglishPhonicsGroup3Route
  EnglishPhonicsGroup4Route: typeof EnglishPhonicsGroup4Route
  EnglishPhonicsGroup5Route: typeof EnglishPhonicsGroup5Route
  EnglishPhonicsGroup6Route: typeof EnglishPhonicsGroup6Route
  EnglishPhonicsGroup7Route: typeof EnglishPhonicsGroup7Route
  EnglishPhonicsRhymesRoute: typeof EnglishPhonicsRhymesRoute
  EnglishPhonicsTrickyWordsRoute: typeof EnglishPhonicsTrickyWordsRoute
  EnglishPhonicsIndexRoute: typeof EnglishPhonicsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/math/': {
      id: '/math/'
      path: '/math'
      fullPath: '/math/'
      preLoaderRoute: typeof MathIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evs/': {
      id: '/evs/'
      path: '/evs'
      fullPath: '/evs/'
      preLoaderRoute: typeof EvsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english/': {
      id: '/english/'
      path: '/english'
      fullPath: '/english/'
      preLoaderRoute: typeof EnglishIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/math/times-tables': {
      id: '/math/times-tables'
      path: '/math/times-tables'
      fullPath: '/math/times-tables'
      preLoaderRoute: typeof MathTimesTablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/math/shapes': {
      id: '/math/shapes'
      path: '/math/shapes'
      fullPath: '/math/shapes'
      preLoaderRoute: typeof MathShapesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/math/place-value': {
      id: '/math/place-value'
      path: '/math/place-value'
      fullPath: '/math/place-value'
      preLoaderRoute: typeof MathPlaceValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/math/numbers': {
      id: '/math/numbers'
      path: '/math/numbers'
      fullPath: '/math/numbers'
      preLoaderRoute: typeof MathNumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/math/counting': {
      id: '/math/counting'
      path: '/math/counting'
      fullPath: '/math/counting'
      preLoaderRoute: typeof MathCountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/math/compare': {
      id: '/math/compare'
      path: '/math/compare'
      fullPath: '/math/compare'
      preLoaderRoute: typeof MathCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/math/addsub': {
      id: '/math/addsub'
      path: '/math/addsub'
      fullPath: '/math/addsub'
      preLoaderRoute: typeof MathAddsubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evs/weather': {
      id: '/evs/weather'
      path: '/evs/weather'
      fullPath: '/evs/weather'
      preLoaderRoute: typeof EvsWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evs/routines': {
      id: '/evs/routines'
      path: '/evs/routines'
      fullPath: '/evs/routines'
      preLoaderRoute: typeof EvsRoutinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evs/plants': {
      id: '/evs/plants'
      path: '/evs/plants'
      fullPath: '/evs/plants'
      preLoaderRoute: typeof EvsPlantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evs/food': {
      id: '/evs/food'
      path: '/evs/food'
      fullPath: '/evs/food'
      preLoaderRoute: typeof EvsFoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evs/family': {
      id: '/evs/family'
      path: '/evs/family'
      fullPath: '/evs/family'
      preLoaderRoute: typeof EvsFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evs/emotions': {
      id: '/evs/emotions'
      path: '/evs/emotions'
      fullPath: '/evs/emotions'
      preLoaderRoute: typeof EvsEmotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evs/body': {
      id: '/evs/body'
      path: '/evs/body'
      fullPath: '/evs/body'
      preLoaderRoute: typeof EvsBodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evs/animals': {
      id: '/evs/animals'
      path: '/evs/animals'
      fullPath: '/evs/animals'
      preLoaderRoute: typeof EvsAnimalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english/tracing': {
      id: '/english/tracing'
      path: '/english/tracing'
      fullPath: '/english/tracing'
      preLoaderRoute: typeof EnglishTracingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english/spelling': {
      id: '/english/spelling'
      path: '/english/spelling'
      fullPath: '/english/spelling'
      preLoaderRoute: typeof EnglishSpellingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english/sight-words': {
      id: '/english/sight-words'
      path: '/english/sight-words'
      fullPath: '/english/sight-words'
      preLoaderRoute: typeof EnglishSightWordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english/sentences': {
      id: '/english/sentences'
      path: '/english/sentences'
      fullPath: '/english/sentences'
      preLoaderRoute: typeof EnglishSentencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english/digraphs': {
      id: '/english/digraphs'
      path: '/english/digraphs'
      fullPath: '/english/digraphs'
      preLoaderRoute: typeof EnglishDigraphsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english/alphabet': {
      id: '/english/alphabet'
      path: '/english/alphabet'
      fullPath: '/english/alphabet'
      preLoaderRoute: typeof EnglishAlphabetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english/phonics/': {
      id: '/english/phonics/'
      path: '/english/phonics'
      fullPath: '/english/phonics/'
      preLoaderRoute: typeof EnglishPhonicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english/phonics/tricky-words': {
      id: '/english/phonics/tricky-words'
      path: '/english/phonics/tricky-words'
      fullPath: '/english/phonics/tricky-words'
      preLoaderRoute: typeof EnglishPhonicsTrickyWordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english/phonics/rhymes': {
      id: '/english/phonics/rhymes'
      path: '/english/phonics/rhymes'
      fullPath: '/english/phonics/rhymes'
      preLoaderRoute: typeof EnglishPhonicsRhymesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english/phonics/group-7': {
      id: '/english/phonics/group-7'
      path: '/english/phonics/group-7'
      fullPath: '/english/phonics/group-7'
      preLoaderRoute: typeof EnglishPhonicsGroup7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english/phonics/group-6': {
      id: '/english/phonics/group-6'
      path: '/english/phonics/group-6'
      fullPath: '/english/phonics/group-6'
      preLoaderRoute: typeof EnglishPhonicsGroup6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english/phonics/group-5': {
      id: '/english/phonics/group-5'
      path: '/english/phonics/group-5'
      fullPath: '/english/phonics/group-5'
      preLoaderRoute: typeof EnglishPhonicsGroup5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english/phonics/group-4': {
      id: '/english/phonics/group-4'
      path: '/english/phonics/group-4'
      fullPath: '/english/phonics/group-4'
      preLoaderRoute: typeof EnglishPhonicsGroup4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english/phonics/group-3': {
      id: '/english/phonics/group-3'
      path: '/english/phonics/group-3'
      fullPath: '/english/phonics/group-3'
      preLoaderRoute: typeof EnglishPhonicsGroup3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english/phonics/group-2': {
      id: '/english/phonics/group-2'
      path: '/english/phonics/group-2'
      fullPath: '/english/phonics/group-2'
      preLoaderRoute: typeof EnglishPhonicsGroup2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english/phonics/group-1': {
      id: '/english/phonics/group-1'
      path: '/english/phonics/group-1'
      fullPath: '/english/phonics/group-1'
      preLoaderRoute: typeof EnglishPhonicsGroup1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english/phonics/cvc-words': {
      id: '/english/phonics/cvc-words'
      path: '/english/phonics/cvc-words'
      fullPath: '/english/phonics/cvc-words'
      preLoaderRoute: typeof EnglishPhonicsCvcWordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english/phonics/blending': {
      id: '/english/phonics/blending'
      path: '/english/phonics/blending'
      fullPath: '/english/phonics/blending'
      preLoaderRoute: typeof EnglishPhonicsBlendingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRoute,
  ParentRoute: ParentRoute,
  ProfilesRoute: ProfilesRoute,
  EnglishAlphabetRoute: EnglishAlphabetRoute,
  EnglishDigraphsRoute: EnglishDigraphsRoute,
  EnglishSentencesRoute: EnglishSentencesRoute,
  EnglishSightWordsRoute: EnglishSightWordsRoute,
  EnglishSpellingRoute: EnglishSpellingRoute,
  EnglishTracingRoute: EnglishTracingRoute,
  EvsAnimalsRoute: EvsAnimalsRoute,
  EvsBodyRoute: EvsBodyRoute,
  EvsEmotionsRoute: EvsEmotionsRoute,
  EvsFamilyRoute: EvsFamilyRoute,
  EvsFoodRoute: EvsFoodRoute,
  EvsPlantsRoute: EvsPlantsRoute,
  EvsRoutinesRoute: EvsRoutinesRoute,
  EvsWeatherRoute: EvsWeatherRoute,
  MathAddsubRoute: MathAddsubRoute,
  MathCompareRoute: MathCompareRoute,
  MathCountingRoute: MathCountingRoute,
  MathNumbersRoute: MathNumbersRoute,
  MathPlaceValueRoute: MathPlaceValueRoute,
  MathShapesRoute: MathShapesRoute,
  MathTimesTablesRoute: MathTimesTablesRoute,
  EnglishIndexRoute: EnglishIndexRoute,
  EvsIndexRoute: EvsIndexRoute,
  MathIndexRoute: MathIndexRoute,
  EnglishPhonicsBlendingRoute: EnglishPhonicsBlendingRoute,
  EnglishPhonicsCvcWordsRoute: EnglishPhonicsCvcWordsRoute,
  EnglishPhonicsGroup1Route: EnglishPhonicsGroup1Route,
  EnglishPhonicsGroup2Route: EnglishPhonicsGroup2Route,
  EnglishPhonicsGroup3Route: EnglishPhonicsGroup3Route,
  EnglishPhonicsGroup4Route: EnglishPhonicsGroup4Route,
  EnglishPhonicsGroup5Route: EnglishPhonicsGroup5Route,
  EnglishPhonicsGroup6Route: EnglishPhonicsGroup6Route,
  EnglishPhonicsGroup7Route: EnglishPhonicsGroup7Route,
  EnglishPhonicsRhymesRoute: EnglishPhonicsRhymesRoute,
  EnglishPhonicsTrickyWordsRoute: EnglishPhonicsTrickyWordsRoute,
  EnglishPhonicsIndexRoute: EnglishPhonicsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
