/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MathRouteImport } from './routes/math'
import { Route as EvsRouteImport } from './routes/evs'
import { Route as EnglishRouteImport } from './routes/english'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MathShapesRouteImport } from './routes/math.shapes'
import { Route as MathNumbersRouteImport } from './routes/math.numbers'
import { Route as MathCountingRouteImport } from './routes/math.counting'
import { Route as MathCompareRouteImport } from './routes/math.compare'
import { Route as MathAddsubRouteImport } from './routes/math.addsub'
import { Route as EnglishTracingRouteImport } from './routes/english.tracing'
import { Route as EnglishSightWordsRouteImport } from './routes/english.sight-words'
import { Route as EnglishSentencesRouteImport } from './routes/english.sentences'
import { Route as EnglishPhonicsRouteImport } from './routes/english.phonics'
import { Route as EnglishAlphabetRouteImport } from './routes/english.alphabet'

const MathRoute = MathRouteImport.update({
  id: '/math',
  path: '/math',
  getParentRoute: () => rootRouteImport,
} as any)
const EvsRoute = EvsRouteImport.update({
  id: '/evs',
  path: '/evs',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishRoute = EnglishRouteImport.update({
  id: '/english',
  path: '/english',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MathShapesRoute = MathShapesRouteImport.update({
  id: '/shapes',
  path: '/shapes',
  getParentRoute: () => MathRoute,
} as any)
const MathNumbersRoute = MathNumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => MathRoute,
} as any)
const MathCountingRoute = MathCountingRouteImport.update({
  id: '/counting',
  path: '/counting',
  getParentRoute: () => MathRoute,
} as any)
const MathCompareRoute = MathCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => MathRoute,
} as any)
const MathAddsubRoute = MathAddsubRouteImport.update({
  id: '/addsub',
  path: '/addsub',
  getParentRoute: () => MathRoute,
} as any)
const EnglishTracingRoute = EnglishTracingRouteImport.update({
  id: '/tracing',
  path: '/tracing',
  getParentRoute: () => EnglishRoute,
} as any)
const EnglishSightWordsRoute = EnglishSightWordsRouteImport.update({
  id: '/sight-words',
  path: '/sight-words',
  getParentRoute: () => EnglishRoute,
} as any)
const EnglishSentencesRoute = EnglishSentencesRouteImport.update({
  id: '/sentences',
  path: '/sentences',
  getParentRoute: () => EnglishRoute,
} as any)
const EnglishPhonicsRoute = EnglishPhonicsRouteImport.update({
  id: '/phonics',
  path: '/phonics',
  getParentRoute: () => EnglishRoute,
} as any)
const EnglishAlphabetRoute = EnglishAlphabetRouteImport.update({
  id: '/alphabet',
  path: '/alphabet',
  getParentRoute: () => EnglishRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/english': typeof EnglishRouteWithChildren
  '/evs': typeof EvsRoute
  '/math': typeof MathRouteWithChildren
  '/english/alphabet': typeof EnglishAlphabetRoute
  '/english/phonics': typeof EnglishPhonicsRoute
  '/english/sentences': typeof EnglishSentencesRoute
  '/english/sight-words': typeof EnglishSightWordsRoute
  '/english/tracing': typeof EnglishTracingRoute
  '/math/addsub': typeof MathAddsubRoute
  '/math/compare': typeof MathCompareRoute
  '/math/counting': typeof MathCountingRoute
  '/math/numbers': typeof MathNumbersRoute
  '/math/shapes': typeof MathShapesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/english': typeof EnglishRouteWithChildren
  '/evs': typeof EvsRoute
  '/math': typeof MathRouteWithChildren
  '/english/alphabet': typeof EnglishAlphabetRoute
  '/english/phonics': typeof EnglishPhonicsRoute
  '/english/sentences': typeof EnglishSentencesRoute
  '/english/sight-words': typeof EnglishSightWordsRoute
  '/english/tracing': typeof EnglishTracingRoute
  '/math/addsub': typeof MathAddsubRoute
  '/math/compare': typeof MathCompareRoute
  '/math/counting': typeof MathCountingRoute
  '/math/numbers': typeof MathNumbersRoute
  '/math/shapes': typeof MathShapesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/english': typeof EnglishRouteWithChildren
  '/evs': typeof EvsRoute
  '/math': typeof MathRouteWithChildren
  '/english/alphabet': typeof EnglishAlphabetRoute
  '/english/phonics': typeof EnglishPhonicsRoute
  '/english/sentences': typeof EnglishSentencesRoute
  '/english/sight-words': typeof EnglishSightWordsRoute
  '/english/tracing': typeof EnglishTracingRoute
  '/math/addsub': typeof MathAddsubRoute
  '/math/compare': typeof MathCompareRoute
  '/math/counting': typeof MathCountingRoute
  '/math/numbers': typeof MathNumbersRoute
  '/math/shapes': typeof MathShapesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/english'
    | '/evs'
    | '/math'
    | '/english/alphabet'
    | '/english/phonics'
    | '/english/sentences'
    | '/english/sight-words'
    | '/english/tracing'
    | '/math/addsub'
    | '/math/compare'
    | '/math/counting'
    | '/math/numbers'
    | '/math/shapes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/english'
    | '/evs'
    | '/math'
    | '/english/alphabet'
    | '/english/phonics'
    | '/english/sentences'
    | '/english/sight-words'
    | '/english/tracing'
    | '/math/addsub'
    | '/math/compare'
    | '/math/counting'
    | '/math/numbers'
    | '/math/shapes'
  id:
    | '__root__'
    | '/'
    | '/english'
    | '/evs'
    | '/math'
    | '/english/alphabet'
    | '/english/phonics'
    | '/english/sentences'
    | '/english/sight-words'
    | '/english/tracing'
    | '/math/addsub'
    | '/math/compare'
    | '/math/counting'
    | '/math/numbers'
    | '/math/shapes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnglishRoute: typeof EnglishRouteWithChildren
  EvsRoute: typeof EvsRoute
  MathRoute: typeof MathRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/math': {
      id: '/math'
      path: '/math'
      fullPath: '/math'
      preLoaderRoute: typeof MathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evs': {
      id: '/evs'
      path: '/evs'
      fullPath: '/evs'
      preLoaderRoute: typeof EvsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english': {
      id: '/english'
      path: '/english'
      fullPath: '/english'
      preLoaderRoute: typeof EnglishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/math/shapes': {
      id: '/math/shapes'
      path: '/shapes'
      fullPath: '/math/shapes'
      preLoaderRoute: typeof MathShapesRouteImport
      parentRoute: typeof MathRoute
    }
    '/math/numbers': {
      id: '/math/numbers'
      path: '/numbers'
      fullPath: '/math/numbers'
      preLoaderRoute: typeof MathNumbersRouteImport
      parentRoute: typeof MathRoute
    }
    '/math/counting': {
      id: '/math/counting'
      path: '/counting'
      fullPath: '/math/counting'
      preLoaderRoute: typeof MathCountingRouteImport
      parentRoute: typeof MathRoute
    }
    '/math/compare': {
      id: '/math/compare'
      path: '/compare'
      fullPath: '/math/compare'
      preLoaderRoute: typeof MathCompareRouteImport
      parentRoute: typeof MathRoute
    }
    '/math/addsub': {
      id: '/math/addsub'
      path: '/addsub'
      fullPath: '/math/addsub'
      preLoaderRoute: typeof MathAddsubRouteImport
      parentRoute: typeof MathRoute
    }
    '/english/tracing': {
      id: '/english/tracing'
      path: '/tracing'
      fullPath: '/english/tracing'
      preLoaderRoute: typeof EnglishTracingRouteImport
      parentRoute: typeof EnglishRoute
    }
    '/english/sight-words': {
      id: '/english/sight-words'
      path: '/sight-words'
      fullPath: '/english/sight-words'
      preLoaderRoute: typeof EnglishSightWordsRouteImport
      parentRoute: typeof EnglishRoute
    }
    '/english/sentences': {
      id: '/english/sentences'
      path: '/sentences'
      fullPath: '/english/sentences'
      preLoaderRoute: typeof EnglishSentencesRouteImport
      parentRoute: typeof EnglishRoute
    }
    '/english/phonics': {
      id: '/english/phonics'
      path: '/phonics'
      fullPath: '/english/phonics'
      preLoaderRoute: typeof EnglishPhonicsRouteImport
      parentRoute: typeof EnglishRoute
    }
    '/english/alphabet': {
      id: '/english/alphabet'
      path: '/alphabet'
      fullPath: '/english/alphabet'
      preLoaderRoute: typeof EnglishAlphabetRouteImport
      parentRoute: typeof EnglishRoute
    }
  }
}

interface EnglishRouteChildren {
  EnglishAlphabetRoute: typeof EnglishAlphabetRoute
  EnglishPhonicsRoute: typeof EnglishPhonicsRoute
  EnglishSentencesRoute: typeof EnglishSentencesRoute
  EnglishSightWordsRoute: typeof EnglishSightWordsRoute
  EnglishTracingRoute: typeof EnglishTracingRoute
}

const EnglishRouteChildren: EnglishRouteChildren = {
  EnglishAlphabetRoute: EnglishAlphabetRoute,
  EnglishPhonicsRoute: EnglishPhonicsRoute,
  EnglishSentencesRoute: EnglishSentencesRoute,
  EnglishSightWordsRoute: EnglishSightWordsRoute,
  EnglishTracingRoute: EnglishTracingRoute,
}

const EnglishRouteWithChildren =
  EnglishRoute._addFileChildren(EnglishRouteChildren)

interface MathRouteChildren {
  MathAddsubRoute: typeof MathAddsubRoute
  MathCompareRoute: typeof MathCompareRoute
  MathCountingRoute: typeof MathCountingRoute
  MathNumbersRoute: typeof MathNumbersRoute
  MathShapesRoute: typeof MathShapesRoute
}

const MathRouteChildren: MathRouteChildren = {
  MathAddsubRoute: MathAddsubRoute,
  MathCompareRoute: MathCompareRoute,
  MathCountingRoute: MathCountingRoute,
  MathNumbersRoute: MathNumbersRoute,
  MathShapesRoute: MathShapesRoute,
}

const MathRouteWithChildren = MathRoute._addFileChildren(MathRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnglishRoute: EnglishRouteWithChildren,
  EvsRoute: EvsRoute,
  MathRoute: MathRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
